apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: fonapp
  labels:
    app: web-app
    environment: dev
    managed-by: argocd
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
