apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: fonapp
  labels:
    app: mongo
    environment: dev
    managed-by: argocd
type: Opaque
data:
  mongo-usr: bW9uZ291c2Vy          # mongouser
  mongo-pwd: bW9uZ29wYXNzd29yZA==  # mongopassword
