name: Terraform Reusable

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      apply:
        required: true
        type: boolean
    secrets: inherit

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: dev_eks_cluster
  SONAR_PROJECT_KEY: dainmusty_microservices-k8s-project
  SONAR_ORGANIZATION: effulgencetech
  TF_VERSION: "1.6.6"
  AWS_ACCOUNT_ID: 651706774390
  ROLE_NAME: microservices-k8s-project-dev-tf-role

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev     # approval happens ONLY when apply:true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: terraform init -upgrade

      - name: Terraform Plan
        working-directory: ${{ inputs.working_directory }}
        run: terraform plan

      - name: Terraform Apply
        if: ${{ inputs.apply == true }}
        working-directory: ${{ inputs.working_directory }}
        run: terraform apply -auto-approve

      - name: Update kubeconfig for EKS
        if: ${{ inputs.apply == true }}
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.CLUSTER_NAME }}
