# name: Docker Build Reusable

# on:
#   workflow_call:
#     inputs:
#       image_name:
#         type: string
#         required: true
#       dockerfile:
#         type: string
#         required: true
#       context:
#         type: string
#         required: true
#     secrets: inherit

# jobs:
#   docker:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build Docker Image
#         run: |
#           docker build \
#             -t ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ github.sha }} \
#             -f ${{ inputs.dockerfile }} \
#             ${{ inputs.context }}

#       - name: Push Image
#         run: docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ github.sha }}

#       - name: Output Image Tag
#         id: image
#         run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
