name: Deploy Infrastructure

on:
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Choose apply after approval"
        required: true
        type: choice
        options:
          - apply

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: dev_eks_cluster
  TF_VERSION: "1.9.7"
  AWS_ACCOUNT_ID: 651706774390
  ROLE_NAME: microservices-project-dev-tf-role
  working_directory: terraform/root-modules/env/dev

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  PlanInfra:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.working_directory }}
        run: terraform init -upgrade

      - name: Terraform Plan
        working-directory: ${{ env.working_directory }}
        run: terraform plan -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: infra-plan
          path: ${{ env.working_directory }}/tfplan



  DeployInfra:
    runs-on: ubuntu-latest
    needs: PlanInfra
    environment: dev   # requires approval
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.terraform_action == 'apply'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.working_directory }}
        run: terraform init -upgrade

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: infra-plan
          path: ${{ env.working_directory }}

      - name: Terraform Apply
        working-directory: ${{ env.working_directory }}
        run: |
          if [ -f "./tfplan" ]; then
            terraform apply -auto-approve tfplan
          else
            terraform apply -auto-approve
          fi

      - name: Update kubeconfig
        working-directory: ${{ env.working_directory }}
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.CLUSTER_NAME }}
