name: Terraform Destroy

on:
  workflow_dispatch:   # manual run

env:
  AWS_REGION: us-east-1
  working_directory: root-modules/env/dev
  TF_VERSION: "1.6.6"
  AWS_ACCOUNT_ID: 651706774390
  ROLE_NAME: microservices-k8s-project-dev-tf-role

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: dev   # <-- approval required

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.working_directory }}
        run: terraform init -upgrade

      - name: Terraform Destroy
        working-directory: ${{ env.working_directory }}
        run: terraform destroy -auto-approve
